export const ACTIONS = {
  REQUEST_LOAN_MODAL: "REQUEST_LOAN_MODAL",
  REPAY_LOAN_MODAL: "REPAY_LOAN_MODAL",
  CALLBACK: "CALLBACK",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  ADD_MONEY_MODAL: "ADD_MONEY_MODAL",
  USER: "USER",
  TOKEN: "TOKEN",
};
